# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Queue-Persistent
version:      0.11
version_from: lib/Data/Queue/Persistent.pm
installdirs:  site
requires:
    DBI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
